fun main() {
  println("1. Adding elements")
  val revolverDrum = RevolverDrum<Int>()
  revolverDrum.addElement(54)
  revolverDrum.addElement(7)
  revolverDrum.addElement(2)
  revolverDrum.addElement(56)
  revolverDrum.addElement(4)
  revolverDrum.addElement(3)
  println("Structure: RevolverDrum<Int>")
  println("Objects: $revolverDrum")
  println("Pointer: ${revolverDrum.getPointer()}\n")
  println("2. Scroll")
  revolverDrum.scroll()
  println("Structure: RevolverDrum<Int>")
  println("Objects: $revolverDrum")
  println("Pointer: ${revolverDrum.getPointer()}\n")
  println("3. Deletion")
  revolverDrum.deleteElement()
  revolverDrum.deleteElement()
  revolverDrum.deleteElement()
  revolverDrum.deleteElement()
  println("Structure: RevolverDrum<Int>")
  println("Objects: $revolverDrum")
  println("Pointer: ${revolverDrum.getPointer()}\n")
  println("4. Supply collection")
  val collection = mutableListOf<Int?>(4, 6, 3, 22, 77, 43, 76, 5)
  println("Before:")
  println("Supply collection: $collection\n")
  println("Structure: RevolverDrum<Int>")
  println("Objects: $revolverDrum")
  println("Pointer: ${revolverDrum.getPointer()}\n")
  revolverDrum.addAllElement(collection)
  println("After add operation performed:")
  println("Supply collection: $collection\n")
  println("Structure: RevolverDrum<Int>")
  println("Objects: $revolverDrum")
  println("Pointer: ${revolverDrum.getPointer()}\n")
  println("5. Extraction")
  val extractedList = revolverDrum.removeAllElement()
  println("The extracted list: $extractedList")
  println("size: ${extractedList.size}\n")
  println("Structure: RevolverDrum<Int>")
  println("Objects: $revolverDrum")
  println("Pointer: ${revolverDrum.getPointer()}")
  println("size: ${revolverDrum.size()}\n")
  println("6. Supply collection 2")
  println("Before:")
  println("Supply collection: $collection\n")
  println("Structure: RevolverDrum<Int>")
  println("Objects: $revolverDrum")
  println("Pointer: ${revolverDrum.getPointer()}\n")
  revolverDrum.addAllElement(collection)
  println("After add operation performed:")
  println("Supply collection: $collection\n")
  println("Structure: RevolverDrum<Int>")
  println("Objects: $revolverDrum")
  println("Pointer: ${revolverDrum.getPointer()}\n")
  println("7. Equals")
  println("Structure: RevolverDrum<Int>")
  println("Objects: $revolverDrum")
  println("Pointer: ${revolverDrum.getPointer()}\n")
  val revolverDrum2 = RevolverDrum<Int>()
  revolverDrum2.addElement(77)
  revolverDrum2.addElement(43)
  revolverDrum2.addElement(76)
  revolverDrum2.addElement(5)
  println("Structure: RevolverDrum<Int>")
  revolverDrum2.scroll()
  println("Objects: $revolverDrum2")
  println("Pointer: ${revolverDrum2.getPointer()}\n")
  println(if (revolverDrum == revolverDrum2) "equals" else "not equals")
}
